version: '3.9'

services:
  api:
    depends_on:
      - db
    build: 
      context: NeKanbanApi
      dockerfile: NeKanban.Api/Dockerfile
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'ConnectionStrings:DefaultConnection=Host=db; Port=5432;Database=nekanban; User Id=postgres; Password=password;'
    ports:
      - "7146:80"
    networks:
      - back-end
  db:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - back-end
  seeder:
      depends_on:
        - db
      build:
        context: NeKanbanApi
        dockerfile: NeKanban.Seeder/Dockerfile
      environment:
        - 'ConnectionStrings:DefaultConnection=Host=db; Port=5432;Database=nekanban; User Id=postgres; Password=password;'
      networks:
        - back-end
  migrator:
      depends_on:
        - db
      build:
        context: NeKanbanApi
        dockerfile: NeKanban.Migrator/Dockerfile
      environment:
        - 'ConnectionStrings:DefaultConnection=Host=db; Port=5432;Database=nekanban; User Id=postgres; Password=password;'
      networks:
        - back-end
networks:
  back-end:
    driver: bridge